cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    a:
      email: a
      name: a
      password: $2b$12$JudKWJNGaCi0eyg.UWr5BOdIOJvXXwWoShofLGS1Aa6tkSOwUhAm.
    aaa:
      email: a
      name: a
      password: $2b$12$Iz3efAk71da9oAgxRf6tO.Re5yiODy2oxmhCNx9F9qrIDqS1VJ44y
    fewmoda:
      email: sanjin@gmail.
      name: shopfw.myshopify.com
      password: $2b$12$PrdHC3DVE8wy7MONTA9Kc.s7O8QETkSO6itYel/Wv9L4tYkrCL7fe
      shop_id: 16038
    ha:
      email: ha
      name: ha
      password: $2b$12$rwFpmlg737t1nlOCN4K.reAJey3.iuyB42CC5n8ghUGBF22awsT.q
    ho:
      email: ho
      name: shopfw.myshopify.com
      password: $2b$12$u4U4D2G0IgC2ewK6SrSume9tDPBANddP0uBbXjC67c26ge969mh4y
    lebeg:
      email: sanjinjf7@gmail.com
      name: lebeg
      password: $2b$12$haQXb0e.QKw9H3VO/YaEQOHtD4ebSjhx/iZG9cypSik3u6/u6oB62
    ni:
      email: ni
      name: ni
      password: $2b$12$7bJkx83xjjjcotviqMYqw.eZxs77GLjExHDSgolwYPAsfDg4wt/xe
    nikola:
      email: nikola
      name: nikola
      password: $2b$12$TidzJVR9QgaY1Lfw4PI.AebTQEdogMp9P9WgRt6BZuBdXe/ewg0f2
preauthorized:
  emails:
  - sanjinjf7@gmail.com
