from .descriptive_tab import *
from .settings import *
from .market_performance_tests import market_performance_tests
from .text_analysis import text_analysis
from .shop_custom_performance_test import shop_custom_performance_test
from .shop_default_performance_tests import shop_default_performance_tests
from .select_shop_and_load_data import select_shop_and_load_data
from .all_platforms import all_platforms
from .analytics import analytics_tab
